Page crash fix
AmericanAirlines/Hangar pull request #154
Opened 2020-09-17 16:31 UTC by Ulfingrad

## Pre-Requisites
- [x] Yes, I updated [Authors.md](../blob/main/Authors.md) **OR** this is not my first contribution
- [x] Yes, I included and/or modified tests to cover relevent code **OR** my change is non-technical
- [x] Yes, I wrote this code entirely myself **OR** I properly attributed these changes in [Third Party Notices](../blob/main/THIRD-PARTY-NOTICES.txt)

## Description of Changes

Added a conditional to ensure that supportRequest's attributes are not accessed when null.

## Related Issues

This change fixes issue #97 which was causing the admin page to crash when attempting to get the next item in queue when no such items exist.

2020-09-17 16:50 UTC, SpencerKaiser requested changes
When we chatted about this issue, @johnkahn made the suggestion to re-trigger the refresh early if this happens; can you add that functionality? Otherwise the button may still show items in the queue and they may click the button again.

2020-09-17 16:50 UTC, SpencerKaiser commented on src/pages/index.tsx
> +                    : 'It appears you are trying to access a support request that does not exist!'}
```suggestion
                  (lastPop.supportRequest !== null) ?  
                    (lastPop.userNotified
                      ? `${lastPop.supportRequest.name} has been notified to come over`
                      : `There was a problem notifying ${lastPop.supportRequest.name}, send them a message and tell them you're ready for them`)
                    : 'It appears you are trying to access a support request that does not exist!'}
```

2020-09-17 17:11 UTC, Ulfingrad commented
@SpencerKaiser Yup, I'll get on those changes as soon as I can!

2020-09-21 14:45 UTC, SpencerKaiser commented
@Ulfingrad remember to reach out to @johnkahn if you have any questions about the final piece of this PR

2020-09-22 15:11 UTC, SpencerKaiser commented on src/pages/index.tsx
> +    }, 3000);
3 seconds is too fast, let's settle for a good middle ground of 10s
```suggestion
    }, 10000);
```

2020-09-22 15:26 UTC, SpencerKaiser approved these changes
Great work you two! @johnkahn is going to review here shortly and he'll merge unless he has other changes 🎉

2020-09-22 15:38 UTC, johnkahn approved these changes

2020-09-22 15:43 UTC, merged