Create linting.yml
AmericanAirlines/Hangar pull request #170
Opened 2020-09-24 01:30 UTC by TheDivexz

Co-Authored-By: Oscar Goddard <52873114+oscargoddard@users.noreply.github.com>

## Pre-Requisites
- [X] Yes, I updated [Authors.md](../blob/main/Authors.md) **OR** this is not my first contribution
- [X] Yes, I included and/or modified tests to cover relevent code **OR** my change is non-technical
- [X] Yes, I wrote this code entirely myself **OR** I properly attributed these changes in [Third Party Notices](../blob/main/THIRD-PARTY-NOTICES.txt)

## Description of Changes

created the linting.yml file in Workflow

## Related Issues

Closes #160

2020-09-24 01:44 UTC, oscargoddard approved these changes

2020-09-24 01:47 UTC, oscargoddard submitted a review, later dismissed

2020-09-25 06:54 UTC, johnkahn requested changes

2020-09-25 06:54 UTC, johnkahn commented on .github/workflows/linting.yml
> +        npm run build
Go ahead and remove`npm run build` since that should happen in the build workflow. Also should remove checkstyle and lint from the build workflow.

2020-09-25 19:44 UTC, SpencerKaiser requested changes
Please review the requested changes and then make sure to update the `Build` workflow to remove lint/checkstyle

2020-09-25 19:44 UTC, SpencerKaiser commented on .github/workflows/linting.yml
> +        npm run lint
Add new line at the end of the file
```suggestion
        npm run lint

```

2020-09-25 19:44 UTC, SpencerKaiser commented on .github/workflows/linting.yml
> +        npm run build
As @johnkahn mentioned, this isn't necessary here
```suggestion
```

2020-09-25 19:48 UTC, SpencerKaiser commented on .github/workflows/linting.yml
> +﻿name: linting
Also don't forget to modify the file name to be `Linting.yml`

2020-09-25 21:27 UTC, SpencerKaiser commented on .github/workflows/Linting.yml
> +        npm run build
```suggestion
```

2020-09-25 21:27 UTC, SpencerKaiser commented on .github/workflows/Linting.yml
> +        npm run lint
```suggestion
        npm run lint

```

2020-09-25 21:28 UTC, SpencerKaiser commented on .github/workflows/Linting.yml
> +﻿name: linting
```suggestion
﻿name: Linting
```

2020-09-25 21:37 UTC, SpencerKaiser commented
@TheDivexz please make sure to remove the checkstyle/lint lines from `Build.yml` and we can merge this!

2020-09-26 00:07 UTC, oscargoddard approved these changes

2020-09-26 00:14 UTC, oscargoddard commented
All the required changes are completed. We are ready to merge.

2020-09-28 14:11 UTC, SpencerKaiser approved these changes

2020-09-28 14:13 UTC, merged