Adds get specific endpoint
AmericanAirlines/Hangar pull request #188
Opened 2020-10-10 19:29 UTC by msiddique933

Updating code on my github to include all the code written, This shoud fix the 179 issue as well

## Pre-Requisites
- [x] Yes, I updated [Authors.md](../blob/main/Authors.md) **OR** this is not my first contribution

- [x] Yes, I included and/or modified tests to cover relevent code **OR** my change is non-technical
- [x] Yes, I wrote this code entirely myself **OR** I properly attributed these changes in [Third Party Notices](../blob/main/THIRD-PARTY-NOTICES.txt)

## Description of Changes
Worked with Austin to add the ability to get a specific support request by ID. 

## Related Issues

 Closes #179 - Get specific endpoint

2020-10-10 19:59 UTC, Ulfingrad commented
We are unsure as to why the linting is angry. Can white space set it off? I don't know if I'm using Eslint correctly, but from what I could tell it didn't have any issues (which it should have based on it failing here).

2020-10-13 04:02 UTC, Ulfingrad commented
Ok, I looked into it a bit more and it turns out I didn't have Eslint set up properly (me dumb). With it now working, there seems to indeed be some issues with the whitespace that we have set up. If I am correct, then it should work with lines 163, 184, 201, and 218 deleted or shortened in the test file (trailing spaces are not allowed, but they are included on those lines). One final note: Eslint was not happy with any line endings on my machine which is due to the expectation of LF instead of CRLF. I tried replacing the value of end_of_line to be CRLF instead of LF in .editorconfig, but Eslint didn't seem to care. I assume these errors should be ignored as they are on literally every line, but is there a way to disable this error altogether that I haven't tried?

2020-10-16 14:56 UTC, johnkahn requested changes
@Ulfingrad For the line endings, you'll need to update the settings of your editor to use LF line endings. In VS Code the setting is called "eol", but our pre-commit hooks automatically convert the line endings to LF, which is why we don't see them in the GitHub check output.

And then looks like you may want to run prettier in the following files. The easiest way to do that is to install the `Prettier` extension in Visual Studio Code, open the file, `ctrl + shift + p` and type `Format Document`.

Files to run prettier on:
`src/api/supportRequest.ts`
`src/tests/api/supportRequest.test.ts`

2020-10-23 15:52 UTC, johnkahn approved these changes

2020-10-27 15:56 UTC, merged