Adds remindUser Endpoint
AmericanAirlines/Hangar pull request #190
Opened 2020-10-19 01:56 UTC by Ulfingrad

## Pre-Requisites
- [x] Yes, I updated [Authors.md](../blob/main/Authors.md) **OR** this is not my first contribution
- [x] Yes, I included and/or modified tests to cover relevent code **OR** my change is non-technical
- [x] Yes, I wrote this code entirely myself **OR** I properly attributed these changes in [Third Party Notices](../blob/main/THIRD-PARTY-NOTICES.txt)

## Description of Changes

Maha and I added a remindUser endpoint which sends the user a message on Slack asking them to come to the booth (and includes the time elapsed since the support request was initially opened).
## Related Issues

Closes #175

2020-10-19 02:09 UTC, Ulfingrad commented
Oops, testing for this is not quite finished! We will work on this once we have the chance to do so.

2020-10-23 16:12 UTC, johnkahn approved these changes

2020-10-27 15:22 UTC, SpencerKaiser commented on src/api/supportRequest.ts
> +    await messageUsers(
```suggestion
    const supportRequest = await SupportRequest.findOne(supportRequestId);
    if (!supportRequest) {
      res.status(404).send('Unable to find matching Support Request');
      return;
    }

    await messageUsers(
```

2020-10-27 15:26 UTC, SpencerKaiser commented on src/tests/api/supportRequest.test.ts
> +
```suggestion

  it('will throw a 500 if the user cannot be messaged', async () => {
     jest.mock('../../slack/utilities/messageUsers');
     const { app } = require('../../app');
     await supertest(app)
       .post('/api/supportRequest/remindUser')
       .send({ supportRequestId: 1e6, relativeTimeElapsedString: 'some time ago' })
       .set({
         Authorization: adminSecret,
         'Content-Type': 'application/json',
       })
       .expect(404);
   });
```

2020-10-27 15:26 UTC, SpencerKaiser commented on src/tests/api/supportRequest.test.ts
> +  it('will throw a 500 if the user cannot be messaged', async () => {
```suggestion
  it('will throw a 404 if the support request cannot be found', async () => {
```

2020-10-27 15:27 UTC, SpencerKaiser approved these changes

2020-10-27 15:29 UTC, SpencerKaiser commented on src/tests/api/supportRequest.test.ts
> +   });
```suggestion
  });

```

2020-10-27 15:30 UTC, SpencerKaiser requested changes

2020-10-27 15:30 UTC, SpencerKaiser commented on src/tests/api/supportRequest.test.ts
> +   });
```suggestion
    jest.mock('../../slack/utilities/messageUsers');
    const { app } = require('../../app');
    await supertest(app)
      .post('/api/supportRequest/remindUser')
      .send({ supportRequestId: 1e6, relativeTimeElapsedString: 'some time ago' })
      .set({
        Authorization: adminSecret,
        'Content-Type': 'application/json',
      })
      .expect(404);
  });
```

2020-10-27 19:55 UTC, Ulfingrad commented
I'm a bit busy today, but I will fix the new problems regarding this issue on Wednesday

2020-11-06 16:09 UTC, SpencerKaiser approved these changes

2020-11-06 16:10 UTC, merged