remove subscribe function
AmericanAirlines/Hangar pull request #221
Opened 2020-11-06 01:20 UTC by TheDivexz

Co-Authored-By: Oscar Goddard <52873114+oscargoddard@users.noreply.github.com>

## Pre-Requisites
- [x] Yes, I updated [Authors.md](../blob/main/Authors.md) **OR** this is not my first contribution
- [x] Yes, I included and/or modified tests to cover relevent code **OR** my change is non-technical
- [x] Yes, I wrote this code entirely myself **OR** I properly attributed these changes in [Third Party Notices](../blob/main/THIRD-PARTY-NOTICES.txt)

## Description of Changes

removes the subscribe and unsubscribe functions

## Related Issues

closes #213

2020-11-06 08:48 UTC, oscargoddard commented
we couldn't figure out what is the problem with the labeler

2020-11-06 16:20 UTC, SpencerKaiser requested changes
Almost ready, we just need to remove a file that's not being used anymore and then we need to create a migration to remove the table from the DB. For the migration, full details can be found in the README, but here's the snippet you'll need: `npm run typeorm migration:generate -- -n MigrationName`

2020-11-06 16:20 UTC, SpencerKaiser commented on src/slack/utilities/getDashboardContext.ts
> -import { Subscriber } from '../../entities/subscriber';
Since this file isn't really being used anymore, just remove it entirely

2020-11-13 17:03 UTC, SpencerKaiser approved these changes

2020-11-13 17:03 UTC, merged