Added the !technicalSupport and !ideaPitch commands
AmericanAirlines/Hangar pull request #227
Opened 2020-11-20 00:48 UTC by Ulfingrad

implementing proper tests

## Pre-Requisites
- [x] Yes, I updated [Authors.md](../blob/main/Authors.md) **OR** this is not my first contribution
- [x] Yes, I included and/or modified tests to cover relevent code **OR** my change is non-technical
- [x] Yes, I wrote this code entirely myself **OR** I properly attributed these changes in [Third Party Notices](../blob/main/THIRD-PARTY-NOTICES.txt)

## Description of Changes

Worked with @smitshah2531 to implement both the technical support and idea pitch queue commands to Discord. We had difficulty writing the tests for this section, so that will have to be implemented soon.

## Related Issues

Closes #211 as well as closes #212

2020-11-23 23:22 UTC, Ulfingrad commented
Still no tests, but it should now but up to date with main.

2020-11-30 23:41 UTC, SpencerKaiser requested changes
Just a few quick changes and we're good to merge!

2020-11-30 23:41 UTC, SpencerKaiser commented on src/discord/events/message/index.ts
> +    description: 'Adds the user to the idea pitch queue',
```suggestion
    description: 'Think you have a good idea? Join a queue to come pitch to our team!',
```

2020-11-30 23:41 UTC, SpencerKaiser commented on src/discord/events/message/index.ts
> +    description: 'Adds the user to the technical support queue',
```suggestion
    description: 'Need help with your hack? Join our tech support queue so our team can help!',
```

2020-11-30 23:41 UTC, SpencerKaiser commented on src/tests/api/supportRequest.test.ts
> -
Revert this change

2020-12-01 16:11 UTC, SpencerKaiser approved these changes

2020-12-01 16:11 UTC, merged