Added remind button on support page and updated remind message
AmericanAirlines/Hangar pull request #287
Opened 2021-02-25 23:46 UTC by tatumwashere

## Pre-Requisites
- [x] Yes, I updated [Authors.md](../blob/main/Authors.md) **OR** this is not my first contribution
- [x] Yes, I included and/or modified tests to cover relevent code **OR** my change is non-technical
- [x] Yes, I wrote this code entirely myself **OR** I properly attributed these changes in [Third Party Notices](../blob/main/THIRD-PARTY-NOTICES.txt)

## Description of Changes

Added a remind button to the UI on the support page. Updated the remindUser message to be mention the voice channel to be joined. Added voiceChannelName parameter to remindUser api and to be used in the remindUser message.
## Related Issues

Closes #74 - Create remind functionality for support queue

`Co-authored-by: Tristen Even <46259649+tristengeven@users.noreply.github.com>`

2021-03-02 19:46 UTC, SpencerKaiser requested changes
We clearly have some tech debt around the Discord/Slack stuff at the moment and I want to clean some stuff up before we try and make the messaging "correct". For now, can you revert the changes to the string and ignore the `voiceChannelName` stuff?

It was also very unclear, but the `voiceChannelName` was really just `supportTicket.name` - one more piece of the tech debt, but just wanted to clarify that we should be retrieving that from the DB, not from the UI's request (which I bet yall would have done had this not been all goofed up).

Other than that this all looks great! Can you post a pic of the UI so @johnkahn can take a look?

2021-03-02 19:46 UTC, SpencerKaiser commented on src/api/supportRequest.ts
> +        voiceChannelName,
```suggestion
```

2021-03-02 19:46 UTC, SpencerKaiser commented on src/api/supportRequest.ts
> +  if (!supportRequestId || !relativeTimeElapsedString || !voiceChannelName) {
```suggestion
  if (!supportRequestId || !relativeTimeElapsedString) {
```

2021-03-02 19:46 UTC, SpencerKaiser commented on src/api/supportRequest.ts
> +  const { supportRequestId, relativeTimeElapsedString, voiceChannelName } = req.body;
```suggestion
  const { supportRequestId, relativeTimeElapsedString } = req.body;
```

2021-03-02 19:46 UTC, SpencerKaiser commented on src/components/SupportQueue/SupportQueueItem.tsx
> +      body: JSON.stringify({ supportRequestId, relativeTimeElapsedString, voiceChannelName }),
```suggestion
      body: JSON.stringify({ supportRequestId, relativeTimeElapsedString }),
```

2021-03-02 19:46 UTC, SpencerKaiser commented on src/tests/api/supportRequest.test.ts
> +        .send({ supportRequestId: 1e6, relativeTimeElapsedString: 'some time ago', voiceChannelName: 'voice channel' })
```suggestion
        .send({ supportRequestId: 1e6, relativeTimeElapsedString: 'some time ago' })
```

2021-03-02 19:46 UTC, SpencerKaiser commented on src/tests/api/supportRequest.test.ts
> +        .send({ supportRequestId: supportRequest.id, relativeTimeElapsedString: 'some time ago', voiceChannelName: 'voice channel' })
```suggestion
        .send({ supportRequestId: supportRequest.id, relativeTimeElapsedString: 'some time ago' })
```

2021-03-02 19:46 UTC, SpencerKaiser commented on src/tests/api/supportRequest.test.ts
> +        .send({ supportRequestId: 1, relativeTimeElapsedString: 'some time ago', voiceChannelName: 'voice channel' })
```suggestion
        .send({ supportRequestId: 1, relativeTimeElapsedString: 'some time ago' })
```

2021-03-03 22:19 UTC, tatumwashere commented
Here is a screenshot of the remind button in the UI

<img width="600" alt="Screen Shot 2021-03-03 at 4 18 47 PM" src="https://user-images.githubusercontent.com/78566681/109880118-24aafe00-7c3c-11eb-980e-01dda11515bc.png">

2021-03-04 15:22 UTC, johnkahn approved these changes
Awesome 👍

2021-03-04 15:56 UTC, SpencerKaiser approved these changes
Great job! :shipit:

2021-03-04 15:57 UTC, merged