Checked if teamData is empty before trying to convert it to Object
AmericanAirlines/Hangar pull request #288
Opened 2021-02-26 06:41 UTC by RazvanPreotu99

## Pre-Requisites
- [x] Yes, I updated [Authors.md](../blob/main/Authors.md) **OR** this is not my first contribution
- [x] Yes, I included and/or modified tests to cover relevent code **OR** my change is non-technical
- [x] Yes, I wrote this code entirely myself **OR** I properly attributed these changes in [Third Party Notices](../blob/main/THIRD-PARTY-NOTICES.txt)

## Description of Changes

Checked if teamData is empty before converting to Object.

## Related Issues

Closes #273 - Support page error when there are no teams.
Co-authored by: Michael Nguyen <50305984+mkn170030@users.noreply.github.com>

2021-03-02 19:53 UTC, SpencerKaiser requested changes
Good catch! There's a slightly more elegant way of handling this, which is using the `??` syntax to swap what would have been `undefined` for an empty object instead. The end result is the same, but we avoid having to indent a big chunk of the code and having to add a new `if`.

The thing I described is called the [`nullish coalescing operator`](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#nullish-coalescing) but here's the gist:

`teamData[0] ?? {}` basically equates to `teamData[0] === undefined ? teamData[0] : {}`

2021-03-02 19:53 UTC, SpencerKaiser commented on src/components/RegisteredTeamsList.tsx
> +      const keys = Object.keys(teamData[0]).filter((key) => !['id', 'name', 'members', 'tableNumber', 'projectDescription'].includes(key));
```suggestion
      const keys = Object.keys(teamData[0] ?? {}).filter((key) => !['id', 'name', 'members', 'tableNumber', 'projectDescription'].includes(key));
```

2021-03-02 19:53 UTC, SpencerKaiser commented on src/components/RegisteredTeamsList.tsx
> +    if (teamData.length != 0) {
Remove this and then save to get the indentation back to normal

2021-03-04 17:52 UTC, johnkahn requested changes
Looks like some weird spacing got committed, you should be able to click `Add suggestion to batch` on each of these and commit them all at once 👍

2021-03-04 17:52 UTC, johnkahn commented on src/components/RegisteredTeamsList.tsx
> +
```suggestion
```

2021-03-04 17:52 UTC, johnkahn commented on src/components/RegisteredTeamsList.tsx
> +
```suggestion

```

2021-03-04 17:52 UTC, johnkahn commented on src/components/RegisteredTeamsList.tsx
> +                )}
```suggestion
                'No teams registered yet... check back soon!'
              )}
```

2021-03-04 17:54 UTC, johnkahn submitted a review, later dismissed
Thanks for doing this, we didn't realize it would be such a short fix 🙈 We'll make sure we have some larger ones going forward.

2021-03-04 17:55 UTC, johnkahn approved these changes

2021-03-04 17:57 UTC, SpencerKaiser approved these changes
Nice catch!

2021-03-04 17:59 UTC, merged