Updated Tests for Team to Mock Database.
AmericanAirlines/Hangar pull request #337
Opened 2021-03-31 03:16 UTC by OlinZ

## Pre-Requisites
- [x] Yes, I updated [Authors.md](../blob/main/Authors.md) **OR** this is not my first contribution
- [x] Yes, I included and/or modified tests to cover relevent code **OR** my change is non-technical
- [x] Yes, I wrote this code entirely myself **OR** I properly attributed these changes in [Third Party Notices](../blob/main/THIRD-PARTY-NOTICES.txt)

## Description of Changes

Updated `team.test.ts` to mock database functions. Need some feedback since we are not sure if we went in the right direction. 

## Related Issues

Related to #231 

`Co-authored-by: Evelio Ramos <44717805+eveliososa@users.noreply.github.com>`

2021-03-31 19:27 UTC, SpencerKaiser requested changes
I think many of the tests aren't testing the functionality and are instead testing the test itself... if you want to see if your test was written well, change the implementation significantly and see if the test break. For example, if you modify this line:
``` typescript
      .set({ activeJudgeCount: () => '"team"."activeJudgeCount" - 1' })
```

and change the decrement to 12 (`'"team"."activeJudgeCount" - 1'`), your tests would still pass...

Take another pass, fix the lint errors, and let us know when you're ready for a new review 🙂

2021-03-31 19:27 UTC, SpencerKaiser commented on src/tests/entities/team.test.ts
> +describe('', () => {
We need to pass a string in here to describe what we're testing. Looks like the previous one was `judging`... should we add that back here?

2021-03-31 19:27 UTC, SpencerKaiser commented on src/tests/entities/team.test.ts
> +    expect(team.activeJudgeCount).toEqual(1);
This really isn't accomplishing much... your `expect`s here are mostly just checking that the query builder was created for the right entity and that your mock method returns the value you asked it to return. Instead, we should be checking other things like `Was the set method called with an object that includes a method with that appropriate name that attempts to decrement the count?`.

2021-03-31 19:27 UTC, SpencerKaiser commented on src/tests/entities/team.test.ts
> +    expect(team.judgeVisits).toEqual(2);
Same comment as the test above;

2021-04-07 20:40 UTC, SpencerKaiser commented on src/entities/team.ts
>    static async updateSelectedTeam(team: Team, hash: string): Promise<UpdateResult> {
@johnkahn I realized that 99% of these methods are just sql... I guess we could check for the values the use, but I'm not sure I see much value in that. Thoughts?

2021-04-07 21:26 UTC, johnkahn approved these changes

2021-04-07 21:30 UTC, merged