Feat: user middleware refactor
AmericanAirlines/Hangar pull request #487
Opened 2023-08-16 18:17 UTC by alexanderallen-aa

## Pre-Requisites
- [x] Yes, I updated [Authors.md](../blob/main/Authors.md) **OR** this is not my first contribution
- [x] Yes, I included and/or modified tests to cover relevent code **OR** my change is non-technical
- [x] Yes, I wrote this code entirely myself **OR** I properly attributed these changes in [Third Party Notices](../blob/main/THIRD-PARTY-NOTICES.txt)

## Description of Changes

## Related Issues

2023-08-16 21:31 UTC, SpencerKaiser requested changes
Super close but we need to avoid changing the existing `POST /users` middleware as that needs to exist separately

2023-08-16 21:31 UTC, SpencerKaiser commented on packages/api/src/api/users/index.ts
Can you revert your changes to this file? This middleware needs to persist as it is; creating a new user will not involve a session that has a user defined

2023-08-16 21:31 UTC, SpencerKaiser commented on packages/api/src/utils/addUser.ts
can you rename as `/src/middleware/userMiddleware.ts`?

2023-08-16 21:31 UTC, SpencerKaiser commented on packages/api/src/utils/addUser.ts
> +  }
Can you utilize `id` instead? Same exact query, just leveraging the id instead of email

2023-08-16 21:31 UTC, SpencerKaiser commented on packages/api/src/utils/addUser.ts
> +  const user = await req.entityManager.findOne( User, userQuery );
You need a `try ... catch` around this with a 500 thrown if something fails

2023-08-16 21:31 UTC, SpencerKaiser commented on packages/api/tests/api/users.ts/index.test.ts
Revert the changes here; this file shouldn't change

2023-08-16 21:31 UTC, SpencerKaiser commented on packages/api/tests/utils/addUser.test.ts
> +  });
Refactor this test to match the style of the others (no `supertest` dependency)

2023-08-18 14:30 UTC, granthill7 approved these changes

2023-08-18 14:30 UTC, merged

2023-08-18 15:29 UTC, SpencerKaiser reviewed
The changes to session middleware here need to be reverted

2023-08-18 15:29 UTC, SpencerKaiser commented on packages/api/jest.config.js
> +    '!./src/middleware/sessionMiddleware.ts',
This should not have been added here; this needs coverage

2023-08-18 15:29 UTC, SpencerKaiser commented on packages/api/src/middleware/sessionMiddleware.ts
> +  if (!req.session?.email || !req.session?.id) {
This breaks the existing functionality; now ID is required when creating a user which will always fail