feat: Users/me endpoint
AmericanAirlines/Hangar pull request #491
Opened 2023-08-18 16:52 UTC by Ansaar-Syed

## Pre-Requisites
- [x] Yes, I updated [Authors.md](../blob/main/Authors.md) **OR** this is not my first contribution
- [x] Yes, I included and/or modified tests to cover relevent code **OR** my change is non-technical
- [x] Yes, I wrote this code entirely myself **OR** I properly attributed these changes in [Third Party Notices](../blob/main/THIRD-PARTY-NOTICES.txt)

## Description of Changes

## Related Issues

2023-08-18 21:01 UTC, granthill7 commented on packages/api/src/api/users/me/index.ts
> +users.get('/me', validateSessionMountUser, returnUser);
Should this just be a '/' endpoint?

2023-08-21 15:05 UTC, SpencerKaiser requested changes

2023-08-21 15:05 UTC, SpencerKaiser commented on packages/api/tests/api/users.ts/me/index.test.ts
> +  mountUserMiddleware: createMockNext(),
This is mocking an unused method; you needed to mock `validateSessionMountUser` - I'm gonna clean that up to make it more obvious but for now just swap the mocked method here and your test should pass

2023-08-21 18:44 UTC, SpencerKaiser approved these changes

2023-08-21 18:53 UTC, merged