feat: Admin Entity
AmericanAirlines/Hangar pull request #493
Opened 2023-08-22 20:41 UTC by Ansaar-Syed

## Pre-Requisites
- [x] Yes, I updated [Authors.md](../blob/main/Authors.md) **OR** this is not my first contribution
- [x] Yes, I included and/or modified tests to cover relevent code **OR** my change is non-technical
- [x] Yes, I wrote this code entirely myself **OR** I properly attributed these changes in [Third Party Notices](../blob/main/THIRD-PARTY-NOTICES.txt)

## Description of Changes

## Related Issues

2023-08-22 21:36 UTC, SpencerKaiser requested changes
Structure is fantastic, but some of the content is a bit off 🤪

2023-08-23 16:51 UTC, Ansaar-Syed commented on packages/database/src/entities/Admin.ts
> +  public id!: string;
Do you want me to remove the Primary key?

2023-08-29 18:12 UTC, SpencerKaiser requested changes
Quick feedback

2023-08-29 18:12 UTC, SpencerKaiser commented on packages/api/src/middleware/adminMiddleware.ts
> +  const adminQuery = { user: req.user?.id };
This is a relatively simply query object; can we just pass this in on line 9 and save the extra line?

2023-08-29 18:12 UTC, SpencerKaiser commented on packages/api/src/middleware/adminMiddleware.ts
> +  }
By sending a status here you effectively end the request, which means calling `next` won't result in a handler that can actually respond with anything 😬 
```suggestion
  if (!userAdmin) {
    // Admin does not exist in the database
    res.sendStatus(403);
    return;
  }
```

2023-08-29 20:35 UTC, SpencerKaiser requested changes
Two teensy things and then we can merge

2023-08-29 20:35 UTC, SpencerKaiser commented on packages/api/src/middleware/adminMiddleware.ts
> +/**
Can you move this comment up on top of the method itself; it won't be detected as a JSDoc comment down here. You'll know if it worked if you hover over `adminMiddleware` and you see your comment

2023-08-29 20:35 UTC, SpencerKaiser commented on packages/api/tests/middleware/adminMiddleware.test.ts
> +    expect(mockRes.sendStatus).toHaveBeenCalledWith(200);
This is likely why your tests are failing

2023-08-29 22:06 UTC, SpencerKaiser approved these changes

2023-08-29 22:09 UTC, merged