feat: POST judgingSessions
AmericanAirlines/Hangar pull request #506
Opened 2023-09-06 20:49 UTC by granthill7

## Pre-Requisites
- [ ] Yes, I updated [Authors.md](../blob/main/Authors.md) **OR** this is not my first contribution
- [ ] Yes, I included and/or modified tests to cover relevent code **OR** my change is non-technical
- [ ] Yes, I wrote this code entirely myself **OR** I properly attributed these changes in [Third Party Notices](../blob/main/THIRD-PARTY-NOTICES.txt)

## Description of Changes

## Related Issues

2023-09-07 17:01 UTC, SpencerKaiser requested changes

2023-09-07 17:35 UTC, granthill7 commented on packages/api/tests/api/expoJudgingSession/index.test.ts
> +      expect(res.status).toEqual(200);
Is the post endpoint not being called by `supertest(app).post('');`?

2023-09-07 17:37 UTC, granthill7 commented on packages/shared/src/schema/expoJudgingSession/post.ts
> +export const expoJudgingSessionPost = post.extend({});
Is that not what it's doing? `import { post } from '../judgingSession';`. I thought any additional things we want to add later will go into that {} object

2023-09-07 17:57 UTC, granthill7 commented on packages/shared/src/schema/judgingSession/post.ts
> +  inviteCode: z.string().uuid(),
How can I validate that? I think v4 UUIDs are all structured the same way

2023-09-07 19:13 UTC, SpencerKaiser commented on packages/api/tests/api/expoJudgingSession/index.test.ts
> +      expect(res.status).toEqual(200);
It is being called by that line but you aren't verifying that it is... if you comment out the line that registers the post endpoint, this test may still succeed. It's just being explicit and guaranteeing the route handler we expect to be called is actually called

2023-09-07 19:14 UTC, SpencerKaiser commented on packages/shared/src/schema/expoJudgingSession/post.ts
> +export const expoJudgingSessionPost = post.extend({});
I'm an idiot; I misread this 😓

2023-09-07 19:15 UTC, SpencerKaiser commented on packages/shared/src/schema/judgingSession/post.ts
> +  inviteCode: z.string().uuid(),
[You did 😅 ](https://github.com/AmericanAirlines/Hangar/pull/506/files#diff-72016482ad3646b06518fa2bee60469e9b4c441f5ee6e1a8b0b899dce66c2974R17)

2023-09-07 19:16 UTC, SpencerKaiser commented on packages/api/src/api/expoJudgingSession/post.ts
> +    // All other errors
```suggestion
```

2023-09-08 15:53 UTC, SpencerKaiser approved these changes

2023-09-08 15:53 UTC, merged