Judging complete
AmericanAirlines/Hangar pull request #558
Opened 2023-10-13 23:20 UTC by alexanderallen-aa

## Pre-Requisites
- [x] Yes, I updated [Authors.md](../blob/main/Authors.md) **OR** this is not my first contribution
- [x] Yes, I included and/or modified tests to cover relevent code **OR** my change is non-technical
- [x] Yes, I wrote this code entirely myself **OR** I properly attributed these changes in [Third Party Notices](../blob/main/THIRD-PARTY-NOTICES.txt)

## Description of Changes

## Related Issues

2023-10-16 21:48 UTC, granthill7 approved these changes

2023-10-16 22:30 UTC, SpencerKaiser requested changes
Mostly small stuff

**Overall I'm really impressed at the work here**... _but_ I question whether it would have been a more maintainable approach to go with an open source library for confetti. I don't have the expertise to review the hardcore CSS stuff here so I'm going to rely on our demo and the expectation that you tested thoroughly.

Finally, just to double check: all of this was written by you and without reference to other projects, correct?

2023-10-16 22:30 UTC, SpencerKaiser commented on packages/web/src/pageUtils/confetti/confetti.tsx
> +  }, []); // eslint-disable-line
Same question as below

2023-10-17 14:51 UTC, SpencerKaiser commented on packages/web/src/pageUtils/confetti/Confetti.tsx
The parent directory still needs the uppercase `C`

2023-10-18 00:58 UTC, SpencerKaiser approved these changes

2023-10-18 00:58 UTC, merged